apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: front
  annotations:
    kubernetes.io/ingress.global-static-ip-name: finance2-ip
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    app: frontend
spec:
  tls: # < placing a host in the TLS config will indicate a certificate should be created
  - hosts:
    - beams.at
    secretName: sampleApp-cert-secret # < cert-manager will store the created certificate in this secret
  rules:
  - host: beams.at
    http:
      paths:
      - path: /*
        backend:
          serviceName: frontend
          servicePort: 80
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: myapp-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT