on: 
  workflow_dispatch:
      branch:
        description: 'branch'     
        default: 'master'
        required: true
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        name: Check out code
        with:
          ref: '${{ github.event.inputs.branch}}'
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and Publish Frontend
        with:
          image: beams
          tags: ${{ github.run_number }}, latest
          registry: ghcr.io
          githubOrg: mreider
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }} 
          directory: ./app
          dockerfile: ./app/Dockerfile
  deploy:
      needs: [build-and-publish]
      runs-on: ubuntu-latest
      steps:
        - name: run number with offset
          env:
              NUM: ${{ github.run_number }}
              ACTIONS_ALLOW_UNSECURE_COMMANDS: True
              PROJECT_ID: ${{ secrets.GKE_PROJECT }}
          run: |
              echo ::set-env name=GITHUB_RUN_NUMBER_WITH_OFFSET::$(($NUM+15))
        - uses: actions/checkout@v2.3.2
          name: Check out code
        - name: Update deployment file (staging)
          run: |
            find ./kubernetes -type f -name '*.yaml' -exec sed -i -E 's|image: ([a-z]*) *$|image: ghcr.io/mreider/\1:<TAG>|' {} \;
            find ./kubernetes -type f -name '*.yaml' -exec sed -i 's|<TAG>|'${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}'|' {} \;
            rm -rf kubernetes_generated/*;
            cp -rf kubernetes/. kubernetes_generated/
        - name: Update deployment files
          uses: test-room-7/action-update-file@v1
          with:
            file-path: kubernetes_generated/*.yaml
            commit-msg: Bump version to ${{ env.GITHUB_RUN_NUMBER_WITH_OFFSET }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - name: setup gcloud cli
          uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
          with:
            service_account_key: ${{ secrets.GKE_SA_KEY }}
            project_id: ${{ secrets.GKE_PROJECT }}
        - name: set kubernetes context
          uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
          with:
            cluster_name: finance
            location: us-central1-c
            credentials: ${{ secrets.GKE_SA_KEY }}
        - name: Deploy
          run: |-
            kubectl apply -f kubernetes_autogenerated -n beams --validate=false
